projectEndings/staticSearch

js/ssSearch.js
xsl/makeSearchPage.xsl

Merge this into master, then master into dev?

Issue 12 clear button

---

configTestWorthReading.xml
docs/howDoIGetIt.html
docs/howDoIUseIt.html
docs/howDoesItWork.html
docs/index.html
docs/schemaSpec.html
docs/search/ssSearch.js
docs/search/staticSearch_report.html
docs/searchFacetFeatures.html
docs/staticSearch.html
docs/textSearchFeatures.html
docs/whatDoesItDo.html
docs/whyWouldIUseIt.html
schema/staticSearch.odd
schema/staticSearch.rng
stemmers/en/ssStemmer.js
stemmers/identity/ssStemmer.js
stemmers/identity/ssStemmer.xsl
test/index.html
test/searchWorthReading.html

Identity stemmers tested and working with the Wendat project.

Issue 40 pluggability

---

docs/howDoIGetIt.html
docs/howDoIUseIt.html
docs/howDoesItWork.html
docs/index.html
docs/schemaSpec.html
docs/searchFacetFeatures.html
docs/staticSearch.html
docs/textSearchFeatures.html
docs/whatDoesItDo.html
docs/whyWouldIUseIt.html
schema/staticSearch.odd
schema/staticSearch.rng
xsl/create_config_xsl.xsl
xsl/json.xsl

This PR enables the use of tf-idf scoring as an alternative algorithm for ranking results as a configurable option.

Add TF-IDF configuration option

---

docs/howDoIGetIt.html
docs/howDoIUseIt.html
docs/howDoesItWork.html
docs/index.html
docs/schemaSpec.html
docs/search/staticSearch_report.html
docs/searchFacetFeatures.html
docs/staticSearch.html
docs/textSearchFeatures.html
docs/whatDoesItDo.html
docs/whyWouldIUseIt.html
schema/staticSearch.odd
schema/staticSearch.rng
test/search.html
xsl/json.xsl
xsl/makeSearchPage.xsl

Implementation of issue #58 (desc filter sort keys) should be ready to go.

Implemented sorting based on sort key or content per issue #58.

---

.gitignore
configTest.xml
docs/howDoI.html
docs/howDoIGetIt.html
docs/howDoIUseIt.html
docs/howDoesItWork.html
docs/index.html
docs/projectsUsingSS.html
docs/schemaSpec.html
docs/search/ssSearch.js
docs/search/staticSearch_report.html
docs/searchFacetFeatures.html
docs/staticSearch.html
docs/textSearchFeatures.html
docs/whatDoesItDo.html
docs/whyWouldIUseIt.html
js/ssSearch.js
schema/staticSearch.odd
schema/staticSearch.rng
test/search.html
xsl/create_config_xsl.xsl
xsl/create_reports.xsl
xsl/json.xsl
xsl/makeSearchPage.xsl
xsl/tokenize.xsl

Issue #88 implementation complete.

Issue88 fragments

---

js/ssHighlight.js
js/ssSearch.js
test/apostrophes.html
test/badthings.html
test/clues.html
test/index.html
test/poems/ditty.html
test/poems/shizukesaya.html
test/poems/twilight.html
test/search.html
test/tables/booze.html
test/tables/decade_year.html

This is now fully-functional -- check the working implementations in Mariage and MyNDIR on Jenkins. It's just missing documentation, which is better done in dev since it's regularly updated and rebuilt there anyway.

Issue 114 ssMark

---

configTest.xml
css/ssSearch.css
js/ssSearch.js
schema/staticSearch.odd
schema/staticSearch.rng
xsl/create_config_xsl.xsl
xsl/makeSearchPage.xsl

Adds the `<resultsPerPage>` to the schema and the appropriate handling in the XSLT / Javascript. Full documentation still needs to be done.

Iss111 pagination

---

schema/staticSearch.odd

Tweaks, copy edits, and adjustments to the documentation.

Documentation tweaks

---

xsl/tokenize.xsl

Basically just a simplification. Tested with Graves. As soon as it's in dev, it'll get tested with everything.

Issue 130 fragmentid

---

configTest.xml
docs/howDoI.html
docs/howDoIGetIt.html
docs/howDoIUseIt.html
docs/howDoesItWork.html
docs/index.html
docs/projectsUsingSS.html
docs/schemaSpec.html
docs/search/ssSearch.js
docs/search/staticSearch_report.html
docs/searchFacetFeatures.html
docs/staticSearch.html
docs/textSearchFeatures.html
docs/whatDoesItDo.html
docs/whyWouldIUseIt.html
js/ssSearch.js
schema/staticSearch.odd
schema/staticSearch.rng
tei/config_tei.xml
tei/tei_stopwords.txt
test/badthings.html
test/search.html
xsl/create_config_xsl.xsl
xsl/makeSearchPage.xsl
xsl/tokenize.xsl

Tested and working in the test set and the TEI set. I did the documentation at the same time in this branch because I needed to add the new element to the schema.

Issue 129 min word length

---

build.xml
buildSchema.xml
docs/howDoI.html
docs/howDoIGetIt.html
docs/howDoIUseIt.html
docs/howDoesItWork.html
docs/index.html
docs/projectsUsingSS.html
docs/schemaSpec.html
docs/search/staticSearch_report.html
docs/searchFacetFeatures.html
docs/staticSearch.html
docs/textSearchFeatures.html
docs/whatDoesItDo.html
docs/whyWouldIUseIt.html
schema/staticSearch.odd
schema/staticSearch.rng
tei/build.xml
test/search.html

@joeytakeda See if you agree with my decision to fail builds using config or configFile rather than ssConfig or ssConfigFile; if so, this PR should complete issue #79. If not, we'll need to think things through more carefully.

Issue 79 prefixes

---

.gitignore
build.xml
test/search.htm_
test/search.html
test/searchWorthReading.htm_

This should keep things a lot cleaner when we're switching branches.

Issue 158 search pages

---

css/ssSearch.css
js/StaticSearch.js
js/ssUtilities.js
xsl/makeSearchPage.xsl

Making a PR to merge this into `dev`

First implementation of splash screen for testing, per issue #156.

---

js/SSTypeAhead.js

Optimizing the loop in SSTypeahead to make loading faster.

Optimize typeahead

---

schema/staticSearch.odd

Adding some documentation re: building from ant. I wasn't sure precisely where it should go, but it seems an OK spot.

Iss180 docs

---

js/StaticSearch.js

This works for me, and doesn't affect any of the tests.

Proposed fix for issue #188.

---

schema/staticSearch.odd
test/clues.html
test/index.html
test/poems/ditty.html
test/poems/shizukesaya.html
test/poems/twilight.html
test/search.htm_
test/tables/booze.html
test/tables/decade_year.html
xsl/json.xsl
xsl/tokenize.xsl

This should add temporary handling for `@data-ssFilterSortKey` per #190 and update the documentation.

Fix for #190

---

js/StaticSearch.js

Implementation of issue #199. Tested in DVPP, which has lots of complexity and details elements.

Issue 199 details elements

---

css/ssSearch.css
xsl/makeSearchPage.xsl

Adding a few labels, a legend, and some CSS handling to pass (at least minimally) automated WCAG AA checks.

Iss201 a11y labels

---

js/StaticSearch.js

Issue 203 popstate

---

docs/staticSearch.html
schema/staticSearch.odd
schema/staticSearch.rng

Some small tweaks to the documentation—done as a PR just to help catch typos :-)

Docs for 1.4

---

configTest.xml
config_documentation.xml
docs/staticSearch.html
schema/staticSearch.odd
schema/staticSearch.rng

This adds the version attribute to the root config element alongside some additional documentation about the root config element.

Add the version attribute to config

---

docs/documentation.css

Initial fixes to make the documentation more human-readable, per issue #224. Obviously we can do more, but this is a start.

Issue 224 doc css

---

xsl/json.xsl

Simple tweak to sort feature filter menus alphabetically.

Sort feature filters alphabetically by default per issue #227.

---

js/StaticSearch.js

I think this is all we need to do, but we may also look at filter values containing characters that should be escaped.

Proposed fix for issue #230.

---

build.xml
test/index.html

Fix debug page generation and add a new debugging page for manual testing.

Issue 234 test pages

---

build.xml

Creating and merging per @joeytakeda.

Issue 236 closure

---

js/StaticSearch.js
xsl/json.xsl
xsl/tokenize.xsl

The two commits here could be squashed.

Issue 240 nuke docId

---

xsl/json.xsl
xsl/tokenize.xsl

Mostly a trivial change, but tracking down that regex on 359 gave me a bit of grief :-)

For #241: Renaming `@data-staticSearch-relativeUri` to `@ss-uri`
